//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Messaging
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FindMessage", Namespace="http://schemas.datacontract.org/2004/07/Messaging")]
    public partial class FindMessage : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Messaging.FindType FindTypeField;
        
        private System.Type TypeField;
        
        private string ValueField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Messaging.FindType FindType
        {
            get
            {
                return this.FindTypeField;
            }
            set
            {
                this.FindTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Type Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FindType", Namespace="http://schemas.datacontract.org/2004/07/Messaging")]
    public enum FindType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ByAutomationId = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ByClassName = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ByDataContextProperty = 2,
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IFindService")]
public interface IFindService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFindService/GetData", ReplyAction="http://tempuri.org/IFindService/GetDataResponse")]
    string GetData(Messaging.FindMessage value);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFindService/GetData", ReplyAction="http://tempuri.org/IFindService/GetDataResponse")]
    System.Threading.Tasks.Task<string> GetDataAsync(Messaging.FindMessage value);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IFindServiceChannel : IFindService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class FindServiceClient : System.ServiceModel.ClientBase<IFindService>, IFindService
{
    
    public FindServiceClient()
    {
    }
    
    public FindServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public FindServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public FindServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public FindServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string GetData(Messaging.FindMessage value)
    {
        return base.Channel.GetData(value);
    }
    
    public System.Threading.Tasks.Task<string> GetDataAsync(Messaging.FindMessage value)
    {
        return base.Channel.GetDataAsync(value);
    }
}
